<%= File.read(File.join(File.dirname(__FILE__), '../../courseware_book.yml')) %>

salesforce_book_name: Biology w Courseware
appearance_code: college_biology
default_course_name: Biology with Courseware
cnx_book_id: 185cbf87-c72e-48f5-b51e-f14f21b5eabd

reading_processing_instructions:
- css: .multiple-choice, .free-response, .art-exercise, .interactive-embedded-homework,
    .scientific, [data-type="glossary"]
  fragments: []
- css: .interactive-embedded-reading
  fragments:
  - node
  - exercise
